import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  scroll: {
    paddingHorizontal: 24,
    alignItems: 'center',
  },
  glowLeft: {
    position: 'absolute',
    top: 120,
    left: -80,
    width: 220,
    height: 220,
    borderRadius: 110,
  },
  glowRight: {
    position: 'absolute',
    top: 260,
    right: -100,
    width: 260,
    height: 260,
    borderRadius: 130,
  },
  headerRow: {
    alignSelf: 'stretch',
    paddingBottom: 8,
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: '800',
    letterSpacing: -0.5,
  },
  headerSubtitle: {
    fontSize: 14,
    marginTop: 2,
  },
  centerContent: {
    alignItems: 'center',
    paddingTop: 36,
    paddingBottom: 8,
    width: '100%',
  },
  medallion: {
    width: 120,
    height: 120,
    borderRadius: 60,
    marginBottom: 24,
    position: 'relative',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.45,
    shadowRadius: 20,
    elevation: 8,
  },
  medallionInner: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#E1B346',
    alignItems: 'center',
    justifyContent: 'center',
    // Gradient approximated via solid amber
  },
  soonBadge: {
    position: 'absolute',
    bottom: -6,
    right: -8,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
  },
  soonText: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
  },
  ucLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 2,
    marginBottom: 6,
  },
  headline: {
    fontSize: 26,
    fontWeight: '800',
    letterSpacing: -0.5,
    textAlign: 'center',
    lineHeight: 32,
    maxWidth: 300,
  },
  body: {
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
    maxWidth: 320,
    marginTop: 12,
    marginBottom: 28,
  },
  roadmapCard: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 16,
    width: '100%',
    marginBottom: 20,
  },
  roadmapLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  roadmapRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
    paddingVertical: 10,
  },
  roadmapDot: {
    width: 20,
    height: 20,
    borderRadius: 10,
    marginTop: 2,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  dotInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  roadmapText: {
    flex: 1,
  },
  roadmapTitle: {
    fontSize: 14,
    fontWeight: '600',
    lineHeight: 20,
  },
  roadmapDetail: {
    fontSize: 11,
    marginTop: 2,
  },
  notifyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderRadius: 14,
    marginBottom: 12,
  },
  notifyText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '700',
  },
});
