import Config

database_url =
  System.get_env("DATABASE_URL") ||
    "postgres://postgres:postgres@localhost:5432/matome_api_dev"

ssl = System.get_env("DATABASE_SSL", "false") in ~w(true 1)

# Point DATABASE_URL at the Supabase Postgres connection string. For pooled
# Supabase connections, use the pgbouncer host/port and keep pool_size modest.
config :matome_api, MatomeApi.Repo,
  url: database_url,
  ssl: ssl,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10")

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :matome_api, MatomeApiWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "nFz3cPuQd6IVxfg7IFBHkKPj8r51tj+iAjVKzJudHFEClX5a3DG+VHC2fzMWglwg",
  # Rebuild /admin assets on change (W0 #1868). install_and_run skips the
  # network install when the binaries are already present under _build.
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:matome, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:matome, ~w(--watch)]}
  ]

# Watch static and templates for browser reloading of the /admin LiveView.
config :matome_api, MatomeApiWeb.Endpoint,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"lib/matome_api_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :matome_api, dev_routes: true

# Admin back-office gate (W3 #1871). Dev-only fallback key for the TOTP
# secret vault — prod fails closed at boot without ADMIN_SECRET_VAULT_KEY
# (see config/runtime.exs).
config :matome_api, MatomeApi.Admin.SecretVault,
  key:
    System.get_env("ADMIN_SECRET_VAULT_KEY") ||
      Base.encode64("dev-only-admin-vault-key-32bytes")

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
