server {
    listen 80;
    listen [::]:80;
    server_name _;

    root /usr/share/nginx/html;
    index matome-studio.html;
    server_tokens off;

    add_header Cache-Control "no-cache" always;
    add_header X-Content-Type-Options "nosniff" always;

    gzip on;
    gzip_static on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_types application/wasm application/javascript text/javascript
               application/json text/css font/ttf image/svg+xml;

    location / {
        try_files $uri $uri/ =404;
    }
}
