/**
 * Client-side summarization is intentionally disabled. Core owns transcript and
 * summary generation after audio upload so no AI endpoint is exposed to mobile.
 */
export const summarizeText = async (text: string): Promise<string> => {
  void text;
  throw new Error("Summaries are generated by Core after recording upload.");
};
