/* eslint-disable */
// Generated by packages/api-client/scripts/generate-api-client.ts from openapi/matome-core-api.json.
// Do not edit this file directly. Run `bun run generate:api` from the workspace root.

export type AuthCredentials = {
  "email": string;
  "password": string;
};

export type AuthResponse = {
  "user": User;
  "access_token": string;
  "refresh_token": string;
  "token_type": "Bearer";
};

export type DownloadResponse = {
  "download": PresignedUrl;
};

export type ErrorResponse = {
  "error": string;
};

export type HealthResponse = {
  "status": string;
};

export type MeResponse = {
  "user": User;
};

export type PresignedUrl = {
  "url": string;
  "method": string;
  "headers"?: Record<string, string>;
  "expires_in": number;
};

export type Recording = {
  "id": number;
  "owner_id": number;
  "title": string;
  "summary"?: string | null;
  "transcript"?: string | null;
  "media_type"?: string | null;
  "storage_key": string;
  "status": RecordingStatus;
  "error_reason"?: string | null;
  "duration"?: number | null;
  "badge"?: string | null;
  "workspace_id"?: number | null;
  "inserted_at": string;
  "updated_at": string;
};

export type RecordingCreateResponse = {
  "recording": Recording;
  "upload": PresignedUrl;
};

export type RecordingInput = {
  "title": string;
  "summary"?: string;
  "transcript"?: string;
  "media_type"?: string;
  "status"?: RecordingStatus;
  "error_reason"?: string;
  "duration"?: number;
  "badge"?: string;
  "workspace_id"?: number;
};

export type RecordingPatch = {
  "title"?: string;
  "summary"?: string;
  "transcript"?: string;
  "media_type"?: string;
  "status"?: RecordingStatus;
  "error_reason"?: string;
  "duration"?: number;
  "badge"?: string;
  "workspace_id"?: number;
};

export type RecordingProcessResponse = {
  "recording": Recording;
  "processing": {
  "queued": boolean;
};
};

export type RecordingResponse = {
  "recording": Recording;
};

export type RecordingStatus = "pending" | "processing" | "done" | "failed";

export type RecordingsResponse = {
  "recordings": Recording[];
};

export type RefreshTokenRequest = {
  "refresh_token": string;
};

export type Space = {
  "id": number;
  "owner_id": number;
  "name": string;
  "description"?: string | null;
  "inserted_at": string;
  "updated_at": string;
};

export type SpaceInput = {
  "name": string;
  "description"?: string;
};

export type SpacePatch = {
  "name"?: string;
  "description"?: string;
};

export type SpaceResponse = {
  "space": Space;
};

export type SpacesResponse = {
  "workspaces": Space[];
};

export type User = {
  "id": number;
  "email": string;
};

export type ValidationErrorResponse = {
  "errors": Record<string, string[]>;
};

export type SearchParams = {
  q?: string;
};

export type MatomeApiClientConfig = {
  baseUrl: string;
  accessToken?: string | (() => string | undefined | Promise<string | undefined>);
  fetch?: typeof fetch;
};

export class MatomeApiError<TBody = unknown> extends Error {
  readonly status: number;
  readonly body: TBody;

  constructor(status: number, body: TBody) {
    super(`Matome API request failed with status ${status}`);
    this.name = "MatomeApiError";
    this.status = status;
    this.body = body;
  }
}

export function createMatomeApiClient(config: MatomeApiClientConfig) {
  const fetchImpl = config.fetch ?? fetch;

  const request = async <TResponse>(
    pathTemplate: string,
    method: string,
    pathParams?: Record<string, string | number>,
    queryParams?: SearchParams,
    body?: unknown
  ): Promise<TResponse> => {
    const path = Object.entries(pathParams ?? {}).reduce(
      (value, [key, pathValue]) => value.replace(`{${key}}`, encodeURIComponent(String(pathValue))),
      pathTemplate
    );
    const url = new URL(path, config.baseUrl.endsWith("/") ? config.baseUrl : `${config.baseUrl}/`);

    for (const [key, value] of Object.entries(queryParams ?? {})) {
      if (value !== undefined) {
        url.searchParams.set(key, value);
      }
    }

    const token =
      typeof config.accessToken === "function" ? await config.accessToken() : config.accessToken;
    const headers = new Headers();

    if (body !== undefined) {
      headers.set("Content-Type", "application/json");
    }

    if (token) {
      headers.set("Authorization", `Bearer ${token}`);
    }

    const response = await fetchImpl(url, {
      method,
      headers,
      body: body === undefined ? undefined : JSON.stringify(body),
    });

    if (response.status === 204) {
      return undefined as TResponse;
    }

    const responseBody = await response.json().catch(() => undefined);

    if (!response.ok) {
      throw new MatomeApiError(response.status, responseBody);
    }

    return responseBody as TResponse;
  };

  return {
    createRecording(body: RecordingInput): Promise<RecordingCreateResponse> {
      return request<RecordingCreateResponse>("/api/recordings", "POST", undefined, undefined, body);
    },
    createSpace(body: SpaceInput): Promise<SpaceResponse> {
      return request<SpaceResponse>("/api/spaces", "POST", undefined, undefined, body);
    },
    deleteRecording(id: number): Promise<void> {
      return request<void>("/api/recordings/{id}", "DELETE", { id }, undefined, undefined);
    },
    deleteSpace(id: number): Promise<void> {
      return request<void>("/api/spaces/{id}", "DELETE", { id }, undefined, undefined);
    },
    getRecording(id: number): Promise<RecordingResponse> {
      return request<RecordingResponse>("/api/recordings/{id}", "GET", { id }, undefined, undefined);
    },
    getRecordingDownloadUrl(id: number): Promise<DownloadResponse> {
      return request<DownloadResponse>("/api/recordings/{id}/download-url", "GET", { id }, undefined, undefined);
    },
    getSpace(id: number): Promise<SpaceResponse> {
      return request<SpaceResponse>("/api/spaces/{id}", "GET", { id }, undefined, undefined);
    },
    listRecordings(params?: SearchParams): Promise<RecordingsResponse> {
      return request<RecordingsResponse>("/api/recordings", "GET", undefined, params, undefined);
    },
    listSpaces(params?: SearchParams): Promise<SpacesResponse> {
      return request<SpacesResponse>("/api/spaces", "GET", undefined, params, undefined);
    },
    login(body: AuthCredentials): Promise<AuthResponse> {
      return request<AuthResponse>("/api/auth/login", "POST", undefined, undefined, body);
    },
    logout(body: RefreshTokenRequest): Promise<void> {
      return request<void>("/api/auth/logout", "POST", undefined, undefined, body);
    },
    me(): Promise<MeResponse> {
      return request<MeResponse>("/api/auth/me", "GET", undefined, undefined, undefined);
    },
    patchRecording(id: number, body: RecordingPatch): Promise<RecordingResponse> {
      return request<RecordingResponse>("/api/recordings/{id}", "PATCH", { id }, undefined, body);
    },
    patchSpace(id: number, body: SpacePatch): Promise<SpaceResponse> {
      return request<SpaceResponse>("/api/spaces/{id}", "PATCH", { id }, undefined, body);
    },
    processRecording(id: number): Promise<RecordingProcessResponse> {
      return request<RecordingProcessResponse>("/api/recordings/{id}/process", "POST", { id }, undefined, undefined);
    },
    refresh(body: RefreshTokenRequest): Promise<AuthResponse> {
      return request<AuthResponse>("/api/auth/refresh", "POST", undefined, undefined, body);
    },
    register(body: AuthCredentials): Promise<AuthResponse> {
      return request<AuthResponse>("/api/auth/register", "POST", undefined, undefined, body);
    },
    searchRecordings(params?: SearchParams): Promise<RecordingsResponse> {
      return request<RecordingsResponse>("/api/recordings/search", "GET", undefined, params, undefined);
    },
    searchSpaces(params?: SearchParams): Promise<SpacesResponse> {
      return request<SpacesResponse>("/api/spaces/search", "GET", undefined, params, undefined);
    },
    updateRecording(id: number, body: RecordingInput): Promise<RecordingResponse> {
      return request<RecordingResponse>("/api/recordings/{id}", "PUT", { id }, undefined, body);
    },
    updateSpace(id: number, body: SpaceInput): Promise<SpaceResponse> {
      return request<SpaceResponse>("/api/spaces/{id}", "PUT", { id }, undefined, body);
    }
  };
}

export type MatomeApiClient = ReturnType<typeof createMatomeApiClient>;
