#!/usr/bin/env bash
# Fill in the local-server deploy environment for docker-compose.localserver.yml.
#   ./.scripts/gen-localserver-env.sh            # write/complete .env.localserver
#   ./.scripts/gen-localserver-env.sh --print    # also dump the file for Dokploy
#
# Idempotent: an existing real value is never touched, so re-running only fills
# what is missing or still holds a CHANGE_ME placeholder. Every other setting
# has a default in the Compose file — see .env.localserver.example for the
# optional tunables (ports, Whisper, LM Studio).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ENV_FILE:-$ROOT/.env.localserver}"
COMPOSE_FILE="$ROOT/docker-compose.localserver.yml"
PRINT=0

usage() {
  sed -n '2,4p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
}

# Progress goes to stderr so `--print` leaves stdout as a clean env dump that
# can be piped straight into the Dokploy API.
report() {
  echo "$1" >&2
}

for arg in "$@"; do
  case "$arg" in
    --print) PRINT=1 ;;
    --file=*) ENV_FILE="${arg#--file=}" ;;
    -h|--help) usage; exit 0 ;;
    *) echo "unknown argument: $arg" >&2; usage >&2; exit 2 ;;
  esac
done

command -v openssl >/dev/null 2>&1 || {
  echo "openssl is required to generate secrets" >&2
  exit 1
}

# The generated secrets are hex, so they stay safe inside DATABASE_URL without
# any percent-encoding.
SECRET_KEYS=(
  POSTGRES_PASSWORD
  GUARDIAN_SECRET_KEY
  ADMIN_OTP_PEPPER
  STORAGE_S3_SECRET_ACCESS_KEY
  AI_ENGINE_DISPATCH_TOKEN
  AI_ENGINE_CALLBACK_SIGNING_SECRET
)

current_value() {
  KEY="$1" awk -F= '
    BEGIN { key = ENVIRON["KEY"] }
    index($0, key "=") == 1 { sub("^" key "=", ""); print; exit }
  ' "$ENV_FILE"
}

# A CHANGE_ME placeholder counts as missing, so a file copied straight from
# .env.localserver.example is completed rather than rejected.
has_value() {
  local value
  value="$(current_value "$1")"
  [ -n "$value" ] && [ "${value#CHANGE_ME}" = "$value" ]
}

set_key() {
  local key="$1" value="$2" tmp
  tmp="$(mktemp "$ENV_FILE.XXXXXX")"
  chmod 600 "$tmp"
  KEY="$key" VALUE="$value" awk '
    BEGIN { key = ENVIRON["KEY"]; value = ENVIRON["VALUE"]; written = 0 }
    index($0, key "=") == 1 && !written { print key "=" value; written = 1; next }
    { print }
    END { if (!written) print key "=" value }
  ' "$ENV_FILE" > "$tmp"
  mv "$tmp" "$ENV_FILE"
}

detect_host_ip() {
  local ip=""
  if command -v ip >/dev/null 2>&1; then
    ip="$(ip route get 1.1.1.1 2>/dev/null |
      awk '{ for (i = 1; i <= NF; i++) if ($i == "src") { print $(i + 1); exit } }')"
  fi
  if [ -z "$ip" ] && command -v hostname >/dev/null 2>&1; then
    ip="$(hostname -I 2>/dev/null | awk '{ print $1 }')"
  fi
  printf '%s' "$ip"
}

mask() {
  local value="$1"
  if [ "${#value}" -le 8 ]; then
    printf '%s' "$value"
  else
    printf '%s…' "${value:0:6}"
  fi
}

if [ ! -f "$ENV_FILE" ]; then
  cat > "$ENV_FILE" <<'HEADER'
# Local-server deploy environment. Generated by .scripts/gen-localserver-env.sh.
# Secrets — never commit. Optional tunables live in .env.localserver.example.
HEADER
  report "created $ENV_FILE"
fi
chmod 600 "$ENV_FILE"

# HOST_IP has to be reachable from browsers on the LAN and from the ai-core
# container, so the loopback address is never a usable answer.
if has_value HOST_IP; then
  report "= kept      HOST_IP=$(current_value HOST_IP)"
else
  host_ip="${HOST_IP:-$(detect_host_ip)}"
  if [ -z "$host_ip" ] || [ "$host_ip" = "127.0.0.1" ]; then
    echo "could not detect a LAN address for HOST_IP" >&2
    echo "re-run with it set explicitly: HOST_IP=192.168.x.y $0" >&2
    exit 1
  fi
  set_key HOST_IP "$host_ip"
  report "+ generated HOST_IP=$host_ip"
fi

for key in "${SECRET_KEYS[@]}"; do
  if has_value "$key"; then
    report "= kept      $key=$(mask "$(current_value "$key")")"
  else
    set_key "$key" "$(openssl rand -hex 32)"
    report "+ generated $key=$(mask "$(current_value "$key")")"
  fi
done

# Core signs callbacks with one secret and authenticates dispatch with the
# other, so a shared value would let either side forge the opposite direction.
if [ "$(current_value AI_ENGINE_DISPATCH_TOKEN)" = "$(current_value AI_ENGINE_CALLBACK_SIGNING_SECRET)" ]; then
  echo "AI_ENGINE_DISPATCH_TOKEN and AI_ENGINE_CALLBACK_SIGNING_SECRET must differ" >&2
  echo "clear one of them in $ENV_FILE and re-run" >&2
  exit 1
fi

if command -v docker >/dev/null 2>&1 && [ -f "$COMPOSE_FILE" ]; then
  if docker compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" config -q 2>/dev/null; then
    report "compose renders with this environment"
  else
    echo "compose could not render — run for the full error:" >&2
    echo "  docker compose --env-file $ENV_FILE -f $COMPOSE_FILE config" >&2
    exit 1
  fi
fi

if [ "$PRINT" -eq 1 ]; then
  echo "--- $ENV_FILE (contains secrets) ---" >&2
  cat "$ENV_FILE"
fi
